#!/bin/sh

# use as .git/hooks/pre-commit

exec 1>&2

RET=0
changed=$(git diff --cached --name-only)
crustified=""

for f in $changed;
do
 if echo $f | grep \\.[c,h]\$ > /dev/null
 then
    # compare result of uncrustify with changes
    #
    # only change any of the invocations here if
    # they are portable across all cmp and shell
    # implementations !
    uncrustify -q -c uncrustify.cfg -f $f | cmp -s $f -
    if test $? = 1 ;
    then
      crustified=" $crustified $f"
      RET=1
    fi
  fi
done

if [ $RET = 1 ];
then
  echo "================================================================"
  echo " Your changes are ugly!                                         "
  echo " Uncrustify your code in your next commit.                      "
  echo " See https://docs.gnunet.org/latest/developers/style.html#coding-style "
  echo "================================================================"
  echo "Example:"
  echo "$ uncrustify --replace -c uncrustify.cfg ${crustified}"
  echo "Do not forget to readd and commit afterwards!"
  exit $RET
fi

# Make sure we have no stupid spelling error
if (which codespell > /dev/null)
then
    export REPORT=$(mktemp /tmp/codespellXXXXXX)
    ( set -o pipefail;
      echo "Checking for spelling errors with codespell..."
      contrib/ci/jobs/0-codespell/job.sh src 2> ${REPORT};
    ) || { echo "Please fix the code spell errors in ${REPORT} first"; exit 2; }
else
    echo "No codespell installed, skipping spell check."
    echo "** Please consider installing codespell! **"
fi

# Do not fail
exit 0
